# Generated by Django 4.1.7 on 2023-03-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherreminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='City name'),
        ),
    ]
