# Generated by Django 4.1.7 on 2023-03-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherreminder', '0002_weather_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='City name'),
        ),
    ]
