# Generated by Django 4.1.7 on 2023-03-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherreminder', '0004_remove_subscription_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='City'),
        ),
    ]
