# Generated by Django 4.1.7 on 2023-03-25 19:27

from django.db import migrations, models
import weatherreminder.models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherreminder', '0005_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_of_subscription',
            field=models.DateTimeField(default=weatherreminder.models.current_time),
        ),
    ]
